-- AlterTable
ALTER TABLE `User` ADD COLUMN `BirthDate` VARCHAR(191) NULL,
    ADD COLUMN `biography` VARCHAR(191) NULL,
    ADD COLUMN `gender` ENUM('MALE', 'FEMALE') NULL DEFAULT 'MALE',
    MODIFY `job` ENUM('UNDEFINED', 'HUSTLER', 'HIPSTER', 'HACKER') NOT NULL DEFAULT 'UNDEFINED';
