export const mentor = [
  "Rahmat Dwi Djatmiko, S.Kom.",
  "Drs. Bambang Siswantoro",
  "Drs. Fuad Choliq",
  "Mokhamad Hadi Wijaya, S.Kom., M.T.",
  "Ifa Choirunnisa, S.ST., M.Pd.",
  "Dra. Peni Wardayani",
  "Ahmad Nasikin, M.Pd.",
  "Aris Puji Santoso, S.Kom.",
  "Yaniko Dimas Yogo Prasetyo, S.Kom.",
  "Emil Bakhtiar Zulkarnain, S.Psi.",
  "Tulus Andrianto, S.Pd.",
  "Rofiqut Thoriq, S.Pd.",
  "Sri Chusnul Haniyah, S.Pd.",
  "Pashatania Fitri Indah Lestari, S.Kom.",
  "Siana Norma Heny, M.Pd.",
  "Hirga Ertama Putra, S.Kom.",
  "Roselina Febriati, S.ST.",
  "Firdausa, S.Pd.",
  "Muhamad Arifin, M.Pd.",
  "Zainul Abidin, S.Kom.",
  "Muhammad Chusni Agus, M.Pd.",
  "Larasati Chairun Nisa, S.Pd.",
  "Ana Wahyuning Sholikhatin, S.Pd.",
  "Nurwidiasih Firstyana Winadi, S.Psi.",
  "Firmansyah Ayatullah, S.Kom.",
  "Tenri Farizatul Warda, S.Pd.",
  "Jevi Wenda Santi, S.Pd.",
  "Rendi Lusbiantoro, M.Pd.",
  "Bias Damiasa, S.Pd.",
  "Adi Nurrachman, S.T., M.Kom.",
  "Ardhian Suseno, M.Pd.",
  "Agus Hari Purwanto, S.Pd.",
  "Nico Rachmacandrana, S.ST.",
  "Achmad Ilham Ramadhani, S.Pd.",
  "Zakaria, S.Pd.",
  "Firman Hadi Amrullah Zainani., S.Kom.",
  "Kinanti Retnaning Widyani, M.Pd.",
  "Qodri Akbar Wadji, S.Kom.",
  "Whyna Agustin, S.Pd.",
  "Joni Setiyawan Saputra, S.Pd.",
  "Tito Tri Prabowo, M.Pd.",
  "Misfalah Thawafa, S.Psi.",
  "M. Masyis Dzul Hilmi, M.Pd.",
  "Adi Trisula, S.Ag.",
  "Ria Cahya Kurnia Rahma, S.Pd.",
  "Achmad Abidin, M.Pd.",
  "Diaur Rahman, S.Pd.",
  "Dafid Bayu Firmansyah, M.Kom.",
  "Andree Rivan Kurniawan, M.Pd.",
  "Endah Kurniawati, M.Pd.",
  "Mohamad Munif, S.Pd.",
  "Muhammad Sonhaji Akbar, M.Kom.",
  "Aulia Mas'adah, S.Kom.",
  "Muhammad Bagus Arifin, S.Pd.",
  "Muhammad Danial Masruroini, S.Pd.",
  "Musfirati Khasanah, S.Pd.",
  "Ina Indra Rustika, S.Pd.",
  "Amalia Ramadhanty, S.Kom.",
  "Dimas Agung Prasetyawan, M.Pd.",
  "Rahardiyan Andzikriadi, S.S.",
  "Chandra Wijaya Kristanto, S.Pd.",
  "Feniliya Mayrini, S.Pd.",
  "Ermawati Dwi Restuningsih, S.Pd.",
  "Lyra Hertin, S.Pd.",
];
