-- AlterTable
ALTER TABLE `User` ADD COLUMN `NIS` VARCHAR(191) NULL,
    ADD COLUMN `NISN` VARCHAR(191) NULL,
    ADD COLUMN `Phone` VARCHAR(191) NULL,
    ADD COLUMN `absent` VARCHAR(191) NULL,
    ADD COLUMN `class` VARCHAR(191) NULL,
    ADD COLUMN `schoolOrigin` VARCHAR(191) NULL,
    MODIFY `photo_profile` VARCHAR(191) NULL;
